Add regexp checks to steps

diff --git a/.github/workflows/1-add-headers.yml b/.github/workflows/1-add-headers.yml
--- a/.github/workflows/1-add-headers.yml
+++ b/.github/workflows/1-add-headers.yml
@@ -33,7 +33,17 @@ jobs:
         with:
           fetch-depth: 0 # Let's get all the branches
 
-      # TBD Check that there is at least one header in the markdown file
+      # Check that there is at least one header in the markdown file
+      - name: Check markdown syntax, header
+        run: |
+          echo "Check that we have at least one header"
+          if [[ "$(cat file.md)" =~ "# [a-zA-Z0-9]"  ]]
+          then
+            echo "Found a header"
+          else
+            echo "Missing a header"
+            exit 204  # We're sending a weird code so it looks different from other "failures"
+          fi
 
       # Update README to close <details id=1>
       # and open <details id=2>
diff --git a/.github/workflows/2-add-an-image.yml b/.github/workflows/2-add-an-image.yml
--- a/.github/workflows/2-add-an-image.yml
+++ b/.github/workflows/2-add-an-image.yml
@@ -33,7 +33,17 @@ jobs:
         with:
           fetch-depth: 0 # Let's get all the branches
 
-      # TBD Check that there is at least one image in the markdown file
+      # Check that there is at least one image in the markdown file
+      - name: Check markdown syntax, image
+        run: |
+          echo "Check that we have at least one image"
+          if [[ "$(cat file.md)" =~ "\!\[.*](.*)"  ]]
+          then
+            echo "Found an image"
+          else
+            echo "Missing an image"
+            exit 204  # We're sending a weird code so it looks different from other "failures"
+          fi
 
       # Update README to close <details id=2>
       # and open <details id=3>
diff --git a/.github/workflows/3-add-a-code-example.yml b/.github/workflows/3-add-a-code-example.yml
--- a/.github/workflows/3-add-a-code-example.yml
+++ b/.github/workflows/3-add-a-code-example.yml
@@ -14,7 +14,7 @@ on:
 
 jobs:
   on_commit_start_markdown_code_example:
-    name: On commit, start markdown, code_example
+    name: On commit, start markdown, code example
 
     # We will only run this action when:
     # 1. This repository isn't the template repository
@@ -33,7 +33,17 @@ jobs:
         with:
           fetch-depth: 0 # Let's get all the branches
 
-      # TBD Check that there is at least one code example in the markdown file
+      # Check that there is at least one code example in the markdown file
+      - name: Check markdown syntax, code example
+        run: |
+          echo "Check that we have at least one header"
+          if [[ "$(cat file.md)" =~ "\`\`\`.*\`\`\`"  ]]
+          then
+            echo "Found a code example"
+          else
+            echo "Missing a code example"
+            exit 204  # We're sending a weird code so it looks different from other "failures"
+          fi
 
       # Update README to close <details id=3>
       # and open <details id=4>
diff --git a/.github/workflows/4-make-a-task-list.yml b/.github/workflows/4-make-a-task-list.yml
--- a/.github/workflows/4-make-a-task-list.yml
+++ b/.github/workflows/4-make-a-task-list.yml
@@ -33,7 +33,17 @@ jobs:
         with:
           fetch-depth: 0 # Let's get all the branches
 
-      # TBD Make sure there is at least one task list item in the file
+      # Make sure there is at least one task list item in the file
+      - name: Check markdown syntax, task list
+        run: |
+          echo "Check that we have at least one task list"
+          if [[ "$(cat file.md)" =~ "- \[ ] "  ]]
+          then
+            echo "Found a task list"
+          else
+            echo "Missing a task list"
+            exit 204  # We're sending a weird code so it looks different from other "failures"
+          fi
 
       # Update README to close <details id=4>
       # and open <details id=5>
